stages:
- test
- build
- deploy

run_tests:
  stage: test
  image: python:3.8
  before_script:
  - "pip install -e ."
  - "pip install pytest pytest-xdist pytest-cov codecov"
  script:
  - py.test -n auto --cov bookmarks
  after_script:
  - codecov --token=$CODECOV_TOKEN

build_image:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/evagelos/pybook .
  - docker push registry.gitlab.com/evagelos/pybook:latest
  only:
  - master

deploy_image:
  stage: deploy
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
  - ssh $SERVER './deploy.sh' gitlab-ci-token $CI_BUILD_TOKEN
  after_script:
  - curl $WEBSITE_URL -fL
  environment:
    name: production
    url: $WEBSITE_URL
  only:
  - master
