image: python:3.5.2

stages:
- test

run_tests:
  stage: test
  before_script:
  - "pip install -r requirements/dev.txt"
  - "pip install pytest-cov"
  - "pip install codecov"
  script:
  - py.test --cov bookmarks
  after_script:
  - codecov --token=$CODECOV_TOKEN