image: python:3.5.2

stages:
- test

run_my_tests:
  stage: test
  script:
  - "pip install -r requirements/dev.txt"
  - "pip install pytest-cov"
  - py.test --cov bookmarks
  
inform_coveralls:
  stage: test
  script:
  - "pip install codecov"
  - codecov --token=CODECOV_TOKEN
  when: on_success