image: python:3.5.2

stages:
- test
- report

run_tests:
  stage: test
  before_script:
  - "pip install -r requirements/dev.txt"
  - "pip install pytest-cov"
  script:
  - py.test --cov bookmarks

update_coverage_report:
  stage: report 
  before_script:
  - "pip install codecov"
  script:
  - codecov --token=$CODECOV_TOKEN