image: python:3.5.2

stages:
- test

run_tests:
  stage: test
  before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/ev-agelos/pybook .
  - docker push registry.gitlab.com/ev-agelos/pybook:latest
  - "pip install -r requirements/dev.txt"
  - "pip install pytest-cov"
  - "pip install codecov"
  script:
  - py.test --cov bookmarks
  after_script:
  - codecov --token=$CODECOV_TOKEN