stages:
- test

run_my_tests:
  stage: test
  before_script:
  - "pip install -r requirements/dev.txt"
  - "pip install pytest-cov"
  - "pip install coveralls"
  script:
  - py.test --cov bookmarks
  
inform_coveralls:
  stage: test
  script:
  - coveralls
  when: on_success