stages:
- test
- build
- deploy

run_tests:
  stage: test
  image: python:3.8-slim-buster
  before_script:
  - pip install -e .
  script:
  - pytest -n auto --cov=./
  after_script:
  - pip install codecov
  - codecov -t=$CODECOV_TOKEN

build_image:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/evagelos/pybook .
  - docker push registry.gitlab.com/evagelos/pybook:latest
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /Release/
  except:
    refs:
      - /^(?!master).+$/

deploy_image:
  stage: deploy
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - ssh $SERVER "echo $CI_BUILD_TOKEN | ./deploy.sh" gitlab-ci-token
  after_script:
  - curl $WEBSITE_URL -fL
  environment:
    name: production
    url: $WEBSITE_URL
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /Release/
  except:
    refs:
      - /^(?!master).+$/


include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
