"""empty message

Revision ID: 295c7c59d48
Revises: None
Create Date: 2015-09-07 22:18:15.738844

"""

# revision identifiers, used by Alembic.
revision = '295c7c59d48'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('bookmarks')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=30), nullable=True),
    sa.Column('title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('users',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=30), nullable=True),
    sa.Column('password', sa.VARCHAR(length=30), nullable=True),
    sa.Column('authenticated', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    ### end Alembic commands ###
